config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
  resources :schedules
  root 'schedules#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  validates :title, presence: true, length: { maximum: 20}
  validates :startdate, presence: true
  validates :enddate, presence: true, comparison: { greater_than_or_equal_to: :startdate }
  validates :schedulememo, length: {maximum: 500}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @schedules = Schedule.all
  end
  
  def new
    @schedule = Schedule.new
  end
  
  def create
    @schedule = Schedule.new(params.require(:schedule).permit(:title, :startdate, :enddate, :allday, :schedulememo))
    if @schedule.save
      redirect_to root_path, notice: 'スケジュールを登録しました'
    else
      render 'new' ,status: :unprocessable_entity
    end
  end
  
  def show
    @schedule = Schedule.find(params[:id])
  end
  
  def edit
    @schedule = Schedule.find(params[:id])
  end
  
  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(params.require(:schedule).permit(:title, :startdate, :enddate, :allday, :schedulememo))
      flash[:notice] = "スケジュールを更新しました"
      redirect_to root_path
    else
      render 'edit' ,status: :unprocessable_entity
    end
  end
  
  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    redirect_to root_path, status: :see_other
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def convert_boolean_to_character(converting_target)
    converting_target ? '○' : ''
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schedule</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <h1>スケジュール管理アプリ</h1>
    </header>
    <%= yield %>
  </body>
</html>

app/views/schedules/edit.html.erb
<h2>予定を編集してください</h2>

<%= render "shared/error", obj: @schedule %>

<%= form_with model: @schedule do |form| %>

 <table>
   <tr>
     <th><%= form.label :title ,"タイトル" %></th>
     <th><%= form.text_field :title %></th>
   </tr>
   
   <tr>
     <th><%= form.label :startdate ,"開始日" %></th>
     <th><%= form.date_field :startdate %></th>
   </tr>
   
   <tr>
     <th><%= form.label :enddate ,"終了日" %></th>
     <th><%= form.date_field :enddate %></th>
   </tr>
   
   <tr>
     <th><%= form.label :allday ,"終日" %></th>
     <th><%= form.check_box :allday, checked:true %></th>
   </tr>
   
   <tr>
     <th><%= form.label :schedulememo ,"スケジュールメモ" %></th>
     <th><%= form.text_area :schedulememo %></th>
   </tr>
 </table>
 
 <p><%= form.submit "保存" %></p>
 <p><%= link_to "キャンセル", :schedules %></p>

<% end %>

app/views/schedules/index.html.erb
<h2>予定一覧</h2>

  <p class="notice"><%= flash[:notice] %></p>

<%= link_to '新規追加' ,new_schedule_path %>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>終日</th>
      <th>更新日時</th>
    </tr>
  </thead>
  
  <tbody>
    <% @schedules.each do |schedule| %>
     <tr>
       <td><%= schedule.id %></td>
       <td><%= schedule.title %></td>
       <td><%= schedule.startdate.strftime("%Y/%m/%d") %></td>
       <td><%= schedule.enddate.strftime("%Y/%m/%d") %></td>
       <td><%= convert_boolean_to_character(schedule.allday) %></td>
       <td><%= schedule.updated_at.to_s(:datetime_jp) %></td>
       <td><%= link_to '詳細', schedule %></td>
       <td><%= link_to '編集', edit_schedule_path(schedule) %></td>
       <td><%= link_to '削除', schedule_path(schedule), data: { turbo_method: 'delete', turbo_confirm: '予定を削除しますか？'}%></td>
     </tr>
    <% end %>
  </tbody>
</table>

<p>予定合計 <%= Schedule.count%> 件</p>
<p>本日の日付 <%= I18n.localize(Date.today) %></p>

app/views/schedules/new.html.erb
<h2>予定の新規追加</h2>

<%= render "shared/error", obj: @schedule %>

<%= form_with model: @schedule do |form| %>

 <table>
   <tr>
     <th><%= form.label :title ,"タイトル" %></th>
     <th><%= form.text_field :title %></th>
   </tr>
   
   <tr>
     <th><%= form.label :startdate ,"開始日" %></th>
     <th><%= form.date_field :startdate %></th>
   </tr>
   
   <tr>
     <th><%= form.label :enddate ,"終了日" %></th>
     <th><%= form.date_field :enddate %></th>
   </tr>
   
   <tr>
     <th><%= form.label :allday ,"終日" %></th>
     <th><%= form.check_box :allday, checked:true %></th>
   </tr>
   
   <tr>
     <th><%= form.label :schedulememo ,"スケジュールメモ" %></th>
     <th><%= form.text_area :schedulememo %></th>
   </tr>
 </table>
 
 <p><%= form.submit "保存" %></p>
 <p><%= link_to "キャンセル", :schedules %></p>

<% end %>

app/views/schedules/show.html.erb
<h2>予定詳細</h2>
 
<table>
  <tr>
    <th>タイトル</th>
    <td><%= @schedule.title %></td>
  </tr>
  <tr>
    <th>開始日</th>
    <td><%= @schedule.startdate.strftime("%Y/%m/%d") %></td>
  </tr>
  <tr>
    <th>終了日</th>
    <td><%= @schedule.enddate.strftime("%Y/%m/%d") %></td>
  </tr>
  <tr>
    <th>終日</th>
    <td><%= convert_boolean_to_character(@schedule.allday) %></td>
  </tr>
  <tr>
    <th>スケジュールメモ</th>
    <td><%= @schedule.schedulememo %></td>
  </tr>
 </table>
 
 <p><%= link_to '編集', edit_schedule_path(@schedule) %></p>
 <p><%= link_to "予定一覧に戻る", :schedules %></p>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
     <p>スケジュールの登録に失敗しました</p>
 <% end %>